name: Redeploy Portainer Stack

on:
  push:
  workflow_dispatch:

jobs:
  redeploy-container:
    name: Redeploy Portainer Stack
    runs-on: ubuntu-latest
    steps:
      - name: Update Stack via AccessToken
        uses: manicmade/portainer-git-stack-redeploy-action@v1.5.3
        with:
          portainerUrl: 'https://portainer.mattyflix.com'
          accessToken: ${{ secrets.PORTAINER_KEY }}
          stackName: 'wigglybot'
