name: Redeploy Container

on: [push]

jobs:
  redeploy-container:
    name: Redeploy Portainer Container
    steps:
      - name: Update Service via Webhook
      uses: newarifrh/portainer-service-webhook@v1
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
