name: Redeploy Portainer Stack

on:
  push:
  workflow_dispatch:

jobs:
  redeploy-container:
    name: Redeploy Portainer Stack
    runs-on: ubuntu-latest
    steps:
      - name: Update Stack via AccessToken
        uses: wirgen/portainer-stack-redeploy-action@v1.1
        with:
          portainerUrl: 'https://portainer.mattyflix.com'
          accessToken: ${{ secrets.PORTAINER_KEY }}
          stackId: 15
